name: ThrowableSpawnEggs
version: ${plugin.version}
main: com.hawkfalcon.tse.Main
description: Makes spawn eggs throwable
authors: [hawkfalcon, SirNickParks, Narimm]
depend: [Monolith]
permissions:
  tse.use:
    default: true
