name: ThrowableSpawnEggs
version: ${plugin.version}
main: com.hawkfalcon.tse.Main
description: ${project.description}
authors: [hawkfalcon, SirNickParks, Narimm]
permissions:
  tse.use:
    default: true
